### ISSUE TITLE
Leave DFU Mode

### ISSUE THREAD

**Issue by darudude** [BrieucDM/DFUSE-commandline#1]
Hi,

Do you know if it is possible to leave DFU mode from the command line? Everything else works perfectly, but right now I have to power cycle the unit.

**Comment by emrelio** [comment]
Did you solve this issue? It would be nice to add this future.

**Comment by emrelio** [comment]
`for /f %%a in ('dir /B /S *.dfu') do %~dp0DfuSeCommand.exe -c -d --fn %%a -l`

Adding "-l" to the end of this line leaving the DFU mode.

**Comment by robokamran** [comment]
Yes add -l and it will leave the DFU mode.
Although, you can use STM32CubeProgrammer. It supports DFU mode in CLI. It cannot reset the device but at least it can make the device detach from USB.
